exitOnError: false
serviceName: "test-matrix-component"
preUpgradeCmds:
    - "echo 'first pre-upgrade command'"
    - "echo 'second pre-upgrade command'"
upgradeCmd: "echo 'this is an upgradeCmd'"
postUpgradeCmds:
    - "echo 'only post-upgrade command'"
